const fs = require('node:fs/promises');
const path = require('node:path');

const SUPPORTED_SITE_ID = 'healthequity';

function toPosixPath(value) {
  return String(value || '').replace(/\\/g, '/');
}

function displayPath(filePath, cwd) {
  const relative = toPosixPath(path.relative(cwd, filePath));
  if (!relative || relative === '.') {
    return '.';
  }
  return relative.startsWith('.') ? relative : `./${relative}`;
}

function siteProfile() {
  return {
    siteId: 'healthequity',
    loginUrl: 'https://my.healthequity.com/ClientLogin.aspx',
    allowedHosts: [
      'my.healthequity.com',
      'member.my.healthequity.com'
    ],
    credentials: {
      identifierKind: 'username',
      usernameSecretKey: 'LOGIN_USERNAME',
      passwordSecretKey: 'LOGIN_PASSWORD',
    },
    otp: {
      required: true,
      deliveryPreference: 'email',
    },
    authenticatedMarkers: {
      urlIncludes: ['/Member/MemberHome.aspx'],
      titleIncludes: ['Member Portal'],
    },
  };
}

function readmeContent() {
  return [
    '# LoginRun Codegen Demo Output',
    '',
    'This folder was generated by `npx @loginrun/codegen demo`.',
    '',
    'The mock demo uses bundled redacted HealthEquity-style artifacts. It does not submit credentials, request OTP, call LoginRun APIs, or require Browserless configuration.',
    '',
    '## Files',
    '',
    '- `login-site.json`: site profile draft for deterministic login onboarding.',
    '- `report.md`: Codegen summary with selected candidates and evidence.',
    '- `fixtures/`: redacted runtime inventory and candidate score artifacts.',
    '- `tests/`: generated fixture regression test.',
    '',
    '## Future Live Commands',
    '',
    '```bash',
    'npx @loginrun/codegen discovery --profile ./loginrun/healthequity/login-site.json',
    'npx @loginrun/codegen e2e --profile ./loginrun/healthequity/login-site.json',
    '```',
    '',
  ].join('\n');
}

function reportContent() {
  return [
    '# LoginRun Codegen Report',
    '',
    '## Summary',
    '',
    'Mock discovery completed with status `ready` for the HealthEquity sample.',
    '',
    'Codegen selected one high-confidence identifier field and one plausible submit control from bundled redacted artifacts. No credentials, OTP codes, Browserless configuration, or LoginRun API calls were used.',
    '',
    '## Detected Workflow Surface',
    '',
    '- Login URL: `https://my.healthequity.com/ClientLogin.aspx`',
    '- Stage: `identifier`',
    '- Selected identifier: username field',
    '- Selected submit: continue button',
    '',
    '## Selected Candidates',
    '',
    'Identifier field:',
    '',
    '```json',
    JSON.stringify({
      semanticRole: 'identifier',
      selector: '#ctl00_modulePageContent_txtUserIdStandard',
      confidence: 0.94,
      evidence: [
        'associated label includes username',
        'visible enabled text input',
        'inside login form context'
      ],
      penalties: []
    }, null, 2),
    '```',
    '',
    'Submit control:',
    '',
    '```json',
    JSON.stringify({
      semanticRole: 'primary_submit',
      selector: '#ctl00_modulePageContent_btnSubmitUsername',
      confidence: 0.91,
      evidence: [
        'button text includes continue',
        'visible enabled submit-like control',
        'follows selected identifier in DOM order'
      ],
      penalties: []
    }, null, 2),
    '```',
    '',
    '## Generated Tests',
    '',
    'The generated fixture test asserts that:',
    '',
    '- the site profile uses the expected HealthEquity login URL',
    '- discovery status is `ready`',
    '- identifier and submit candidates exceed the confidence threshold',
    '- generated fixtures do not contain credential values',
    '',
    '## Runtime Loop Mapping',
    '',
    'The future live runner will keep browser actions deterministic:',
    '',
    '```text',
    'Browser Runtime -> Runtime Inventory -> Candidate Identifier -> Page / Stage Classifier -> State Machine -> Action Planner -> Action Executor -> Page Stability / Redirect Wait',
    '```',
    '',
    'The coding agent operates outside that runtime loop. It reads artifacts, reasons about failures, patches profiles or generic workflow logic, runs tests, and reruns discovery.',
    '',
    '## Future Live Commands',
    '',
    '```bash',
    'npx @loginrun/codegen discovery --profile ./loginrun/healthequity/login-site.json',
    'npx @loginrun/codegen e2e --profile ./loginrun/healthequity/login-site.json',
    '```',
    '',
  ].join('\n');
}

function generatedTestContent() {
  return [
    "import assert from 'node:assert/strict';",
    "import fs from 'node:fs';",
    "import path from 'node:path';",
    "import test from 'node:test';",
    "import { fileURLToPath } from 'node:url';",
    '',
    'const __dirname = path.dirname(fileURLToPath(import.meta.url));',
    "const root = path.resolve(__dirname, '..');",
    "const profile = JSON.parse(fs.readFileSync(path.join(root, 'login-site.json'), 'utf8'));",
    "const scores = JSON.parse(fs.readFileSync(path.join(root, 'fixtures', 'landing-candidate-scores.json'), 'utf8'));",
    "const inventory = JSON.parse(fs.readFileSync(path.join(root, 'fixtures', 'landing-runtime-inventory.json'), 'utf8'));",
    '',
    "test('HealthEquity mock discovery is ready', () => {",
    "  assert.equal(profile.siteId, 'healthequity');",
    "  assert.equal(profile.loginUrl, 'https://my.healthequity.com/ClientLogin.aspx');",
    "  assert.equal(scores.discovery.status, 'ready');",
    "  assert.equal(scores.discovery.selectedIdentifier.semanticRole, 'identifier');",
    "  assert.ok(scores.discovery.selectedIdentifier.confidence >= 0.9);",
    "  assert.equal(scores.discovery.selectedSubmit.semanticRole, 'primary_submit');",
    "  assert.ok(scores.discovery.selectedSubmit.confidence >= 0.9);",
    "});",
    '',
    "test('mock fixtures do not contain credential values', () => {",
    "  const serialized = JSON.stringify({ inventory, scores });",
    "  assert.equal(serialized.includes('LOGIN_PASSWORD_VALUE'), false);",
    "  assert.equal(serialized.includes('OTP_CODE_VALUE'), false);",
    "});",
    '',
  ].join('\n');
}

async function writeJson(filePath, value) {
  await fs.writeFile(filePath, `${JSON.stringify(value, null, 2)}\n`);
}

async function copyFixture(name, destinationDir) {
  const sourcePath = path.resolve(__dirname, '..', 'fixtures', SUPPORTED_SITE_ID, name);
  const destinationPath = path.join(destinationDir, name);
  await fs.copyFile(sourcePath, destinationPath);
  return destinationPath;
}

async function runDemo(input = {}) {
  const site = String(input.site || SUPPORTED_SITE_ID).trim().toLowerCase();
  if (site !== SUPPORTED_SITE_ID) {
    const error = new Error(
      `Unsupported site: ${site}. Mock demo mode currently supports "healthequity" only.`
    );
    error.exitCode = 1;
    throw error;
  }

  const cwd = path.resolve(input.cwd || process.cwd());
  const outputRoot = path.resolve(cwd, input.out || './loginrun');
  const siteDir = path.join(outputRoot, SUPPORTED_SITE_ID);
  const fixturesDir = path.join(siteDir, 'fixtures');
  const testsDir = path.join(siteDir, 'tests');
  await fs.mkdir(fixturesDir, { recursive: true });
  await fs.mkdir(testsDir, { recursive: true });

  const files = {
    profile: path.join(siteDir, 'login-site.json'),
    report: path.join(siteDir, 'report.md'),
    readme: path.join(siteDir, 'README.md'),
    runtimeInventory: path.join(fixturesDir, 'landing-runtime-inventory.json'),
    candidateScores: path.join(fixturesDir, 'landing-candidate-scores.json'),
    test: path.join(testsDir, 'healthequity.discovery.test.ts'),
  };

  await writeJson(files.profile, siteProfile());
  await fs.writeFile(files.report, reportContent());
  await fs.writeFile(files.readme, readmeContent());
  await copyFixture('landing-runtime-inventory.json', fixturesDir);
  await copyFixture('landing-candidate-scores.json', fixturesDir);
  await fs.writeFile(files.test, generatedTestContent());

  const stdout = input.stdout || (line => console.log(line));
  stdout([
    'LoginRun Codegen demo complete',
    '',
    'Generated:',
    `  ${displayPath(files.profile, cwd)}`,
    `  ${displayPath(files.report, cwd)}`,
    `  ${displayPath(fixturesDir, cwd)}/`,
    `  ${displayPath(testsDir, cwd)}/`,
    '',
    'Result:',
    '  discovery: ready',
    '  selected identifier: username field',
    '  selected submit: continue button',
  ].join('\n'));

  return {
    status: 'ready',
    siteId: SUPPORTED_SITE_ID,
    outputDir: siteDir,
    files,
  };
}

module.exports = {
  runDemo,
  siteProfile,
};
